<?php

namespace backend\controllers;

use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\HttpHeaderAuth;
use yii\filters\auth\QueryParamAuth;

class AuthController extends \yii\rest\Controller
{

    public function init()
    {
        parent::init();
        \Yii::$app->user->enableSession = false;
    }

    /**
     * @return array|array[]
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        //认证
        $behaviors['authenticator'] = [
            'class'=>\backend\filters\auth\ExCompositeAuth::class,
            'authMethods'=> [
                HttpHeaderAuth::class,
                HttpBearerAuth::class,
                QueryParamAuth::class,
                HttpBasicAuth::class,
            ]
        ];

        return $behaviors;
    }


    /**
     * @return array[]
     */
    public function verbs()
    {
        return [
            'index' => ['get'],
            'view' => ['get'],
            'create' => ['post'],
            'update' => ['put'],
            'delete' => ['delete'],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action) == false) { // TODO: Change the autogenerated stub
            return false;
        }

        return $this->checkAccess();
    }


    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * @param $action
     * @return true
     * @throws \yii\web\ForbiddenHttpException
     */
    public function checkAccess()
    {
        $action = \Yii::$app->controller->action->id;
        $module = \Yii::$app->controller->module->id;
        $controller = \Yii::$app->controller->id;
        $permission = $module == \Yii::$app->id ? $controller .'-'. $action: $module .'-'. $controller . '-' . $action;
        if(\Yii::$app->user->can(strtolower($permission)) == false){
            throw new \yii\web\ForbiddenHttpException('对不起，您没有权限访问该页面!');
        }
        return true;
    }
}