<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "wx_lesson".
 *
 * @property int $id
 * @property int $grade_id
 * @property int $book_id
 * @property string $lesson_name
 * @property string $lesson_content
 * @property string $lesson_image
 * @property string $created_at
 */
class Lesson extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'wx_lesson';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['book_id', 'lesson_name', 'lesson_content', 'lesson_image', 'created_at'], 'required'],
            [['book_id'], 'integer'],
            [['lesson_content'], 'string'],
            [['created_at'], 'safe'],
            [['lesson_name'], 'string', 'max' => 32],
            [['lesson_image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'book_id' => 'Book',
            'lesson_name' => 'Lesson Name',
            'lesson_content' => 'Lesson Content',
            'lesson_image' => 'Lesson Image',
            'created_at' => 'Create At',
        ];
    }

    public function beforeValidate()
    {
        if($this->isNewRecord){
            $this->created_at = date('Y-m-d H:i:s');
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function getBook()
    {
        return $this->hasOne(Book::class, ['id'=>'book_id']);
    }
}
